[project]
authors = ["Hamada Saleh <hamada.kslh@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "rustlib"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
rust = "*"
python = "*"
ipykernel = "*"
jupyter = "*"
maturin = "*"
pip = ">=24.3.1,<25"
